function Hd = filter_50
%FILTER_50 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-Jun-2021 15:13:30

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 256;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 8;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
